### ISSUE TITLE
TypeError: The value of a feed cannot be a tf.Tensor object.

### ISSUE THREAD

**Issue by wangWilson** [neuleaf/MobileNetV2#10]
START TRAINING...
Traceback (most recent call last):
  File "train_mobilenetv2.py", line 124, in <module>
    main()
  File "train_mobilenetv2.py", line 102, in main
    _lr,_ = sess.run([lr,train_op], feed_dict=feed_dict)
  File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1070, in _run
    raise TypeError('The value of a feed cannot be a tf.Tensor object. '
TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.
训练的过程中出现这个错误，您之前有遇到过么？

**Comment by BlueBubbleWei** [comment]
tensorflow读取方式有三种，这种是读取文件不再是feed所以，他这个代码问题太过！

**Comment by quliulangle** [comment]
feed_dict内的数据要先run一下

**Comment by quliulangle** [comment]
> START TRAINING...
> Traceback (most recent call last):
> File "train_mobilenetv2.py", line 124, in 
> main()
> File "train_mobilenetv2.py", line 102, in main
> _lr,_ = sess.run([lr,train_op], feed_dict=feed_dict)
> File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
> run_metadata_ptr)
> File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1070, in _run
> raise TypeError('The value of a feed cannot be a tf.Tensor object. '
> TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.
> 训练的过程中出现这个错误，您之前有遇到过么？

feed_dict内的数据要先run一下

**Comment by ShockeenLee** [comment]
> > START TRAINING...
> > Traceback (most recent call last):
> > File "train_mobilenetv2.py", line 124, in
> > main()
> > File "train_mobilenetv2.py", line 102, in main
> > _lr,_ = sess.run([lr,train_op], feed_dict=feed_dict)
> > File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
> > run_metadata_ptr)
> > File "C:\Users\dellc4130\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1070, in _run
> > raise TypeError('The value of a feed cannot be a tf.Tensor object. '
> > TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.
> > 训练的过程中出现这个错误，您之前有遇到过么？
> 
> feed_dict内的数据要先run一下

请问具体怎么做，谢谢

**Comment by neuleaf** [comment]
抱歉，代码过时，不建议在使用
