### ISSUE TITLE
我用自己的数据集训练，做2分类任务，但是测试是无论输入什么样的图像，都被分为第一类

### ISSUE THREAD

**Issue by quliulangle** [neuleaf/MobileNetV2#15]
哪怕我用训练集中的图像测试，也同样都被分为第一类。
真是神奇………

**Comment by xiaoluojun** [comment]
你好，请问你用的是tensorflow的那个版本？

**Comment by Paul0629** [comment]
@quliulangle 我也是，训练的模型测试集准确率一直是0.5左右抖动啊

**Comment by ShawKai666** [comment]
我也是这种情况，谁能回答一下怎么回事啊

**Comment by Paul0629** [comment]
@quliulangle @xiaoluojun @ShockeenLee @neuleaf 你们解决了这个问题吗？怎么训练的时候loss和accuracy都不带怎么变的

**Comment by quliulangle** [comment]
> @quliulangle @xiaoluojun @ShockeenLee @neuleaf 你们解决了这个问题吗？怎么训练的时候loss和accuracy都不带怎么变的

没有解决   网络结构是没问题的  可能是数据预处理的问题？？？？？  不太清楚

**Comment by quliulangle** [comment]
> 你好，请问你用的是tensorflow的那个版本？

1.5.0

**Comment by neuleaf** [comment]
@all，感谢分享。模型不收敛可能是train部分代码的问题。但是该代码已经过时了，现在建议参考官方的models。
