### ISSUE TITLE
用猫狗数据做二分类，测试的准确率一直在0.5抖动

### ISSUE THREAD

**Issue by Paul0629** [neuleaf/MobileNetV2#17]
@neuleaf 我用您的代码，用猫狗数据做二分类，测试的准确率一直在0.5抖动，感觉训练了3万次都没什么变化啊，请问您可能是什么原因？

**Comment by Paul0629** [comment]
试了很多数据集，loss和accuracy都没怎么变化，，实在是找不到原因了，大神帮帮我呀 @neuleaf @neuleaf @neuleaf

**Comment by neuleaf** [comment]
抱歉，最近一直在做别的事情。现在建议用官方的代码，就得api已经变化很多了。如果需要帮助可以再留言
