### ISSUE TITLE
in this github, we can not get main.py 

### ISSUE THREAD

**Issue by jackft2** [neuleaf/MobileNetV2#6]
in this github, we can not get main.py
shall we use the main function in train_mobilenetv2.py to train?

**Comment by jiangtaoo2333** [comment]
好像也不能运行，bug真多

**Comment by neuleaf** [comment]
@jackft2 yes, use train_mobilenetv2.py instead.

**Comment by HongWeiDong0606** [comment]
> 好像也不能运行，bug真多



> in this github, we can not get main.py
> shall we use the main function in train_mobilenetv2.py to train?
may i ask you how to 

> @jackft2 yes, use train_mobilenetv2.py instead.

Hello,may i ask how to make tfrecord file?i'm failed when i follow the readme

**Comment by neuleaf** [comment]
@HongWeiDong0606 抱歉，代码有些问题而且太过时了。建议参考官方的models。
