### ISSUE TITLE
mobilenet_v2.py 19行

### ISSUE THREAD

**Issue by xiaofateng** [neuleaf/MobileNetV2#8]
neuleaf，你好。
感谢你的开源贡献。
有一处疑问
mobilenet_v2.py 19行
net = res_block(net, exp, 64, 1, is_train, name='res5_1')，这里1 应该是 2 吧？

24行
net = res_block(net, exp, 96, 2, is_train, name='res6_1')  # size/16  这里的2应该是1 吧？

感谢答复！

**Comment by TachibanaYoshino** [comment]
对的，你是对的，我对着论文中的结构表看了一下，你是对的。而且还有个问题，第32行：net = res_block(net, exp, 320, 1, is_train, name='res8_1', shortcut=False)  这既然是个bottleneck block，那么它当然是有shortcut的，这为何定为false？
